### ISSUE TITLE
Make Matplotlib mode properly usable

### ISSUE THREAD

**Issue by teutoburg** [teutoburg/prepipy#14]
## Problem
The MPL mode is currently a bit of a mess.

## Tasks to fix this
To push towards a release, the following things absolutely need to be fixed:
- [ ] Cleanup of class in general.
- [ ] Reworking the main image generation method.
- [ ] Fix the padding issue.
- [ ] Make it properly configurabe.

## Features to implement
The following features should be implemented to make it properly useable:
- [ ] #1 
- [ ] Choice of using pixel or WCS frame for images.
- [ ] Choice of using histogram alongside images.
- [ ] Choice of displaying a before-after view from stretching, ideally with multiple stretch modes.

## Nice-to-haves
These things could be added but also at a later release:
- [ ] Possibility to display multiple sources in one figure, if feasible (low priority).
